In [1]:
!python3 -m pip install -U python-woc pandas matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-woc in /home/kbissonn/.local/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: pandas in /home/kbissonn/.local/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/kbissonn/.local/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /home/kbissonn/.local/lib/python3.9/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /home/kbissonn/.local/lib/python3.9/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /home/kbissonn/.local/lib/python3.9/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /home/kbissonn/.local/lib/python3.9/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /home/kbissonn/.local/lib/python3.9/site-packages (from python-woc) (4.70.0)
Requirement already satisfied: anyio in /home/kbissonn/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: certifi in /home/kbissonn/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/kbissonn/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2.10)
Requirement already satisfied: h11>=0.16 in /home/kbissonn/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/lib64/python3.9/site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: tzdata>=2022.7 in /home/kbissonn/.local/lib/python3.9/site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/kbissonn/.local/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.9/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/kbissonn/.local/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib64/python3.9/site-packages (from matplotlib) (1.4.1)
Requirement already satisfied: packaging>=20.0 in /home/kbissonn/.local/lib/python3.9/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/lib64/python3.9/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.9/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/kbissonn/.local/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.14.1)

In [2]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = ['JuliaGaussianProcesses/AbstractGPs.jl', 'pyushkevich/itksnap', 'darrencroton/sage', 'nanograv/enterprise', 'nsidc/mapxmaps', 'kinnala/scikit-fem', 'alibaba/GraphScope', 'TuringLang/Bijectors.jl', 'sandialabs/pecos', 'sicara/tuto-fsl']
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

,sha1,project
0,0042246a0dd64b15adbeea4a0c71a81889dab790,juliagaussianprocesses_abstractgps.jl

In [3]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  6%|███████▋                                                                                                                       | 198/3294 [03:24<54:04,  1.05s/it]

Got Errors {'1cd311bbbdb6c340a494d4689c1f2b7e4ce82121': 'Key 1cd311bbbdb6c340a494d4689c1f2b7e4ce82121 not found in /da5_fast/All.sha1c/commit_28.tch'}

  6%|███████▋                                                                                                                       | 199/3294 [03:25<53:56,  1.05s/it]

Got Errors {'1d57c3f5123d4672083233b1dd8322242dc257d1': 'Key 1d57c3f5123d4672083233b1dd8322242dc257d1 not found in /da5_fast/All.sha1c/commit_29.tch'}

  7%|████████▍                                                                                                                      | 219/3294 [03:46<53:30,  1.04s/it]

Got Errors {'31a0f4151c2a1a105d60cd5eed015518626557fa': 'Key 31a0f4151c2a1a105d60cd5eed015518626557fa not found in /da5_fast/All.sha1c/commit_49.tch'}

  8%|█████████▊                                                                                                                     | 254/3294 [04:22<52:45,  1.04s/it]

Got Errors {'55bf8c1c1ca404d175b073a7d617d2abc02931d0': 'Key 55bf8c1c1ca404d175b073a7d617d2abc02931d0 not found in /da5_fast/All.sha1c/commit_85.tch'}

 10%|████████████▍                                                                                                                  | 321/3294 [05:32<51:41,  1.04s/it]

Got Errors {'9640a4b9b43500ff5f4e426ae8fe3b68363aa070': 'Key 9640a4b9b43500ff5f4e426ae8fe3b68363aa070 not found in /da5_fast/All.sha1c/commit_22.tch'}

 10%|████████████▉                                                                                                                  | 336/3294 [05:48<51:09,  1.04s/it]

Got Errors {'a54ded3f3f4d190bdfdecd00b3a763a45b466b3f': 'Key a54ded3f3f4d190bdfdecd00b3a763a45b466b3f not found in /da5_fast/All.sha1c/commit_37.tch'}

 12%|███████████████▊                                                                                                               | 409/3294 [07:04<50:05,  1.04s/it]

Got Errors {'ebb6c601b8534190c99d94269ec4d3c63eb5acdc': 'Key ebb6c601b8534190c99d94269ec4d3c63eb5acdc not found in /da5_fast/All.sha1c/commit_107.tch'}

 17%|█████████████████████▎                                                                                                         | 553/3294 [09:34<47:37,  1.04s/it]

Got Errors {'4dd01a166466fc84e63325d726b4e83ca8d55cb3': 'Key 4dd01a166466fc84e63325d726b4e83ca8d55cb3 not found in /da5_fast/All.sha1c/commit_77.tch'}

 18%|██████████████████████▍                                                                                                        | 583/3294 [10:05<46:59,  1.04s/it]

Got Errors {'73b589bfd5910adcb769b294ab98d70717fded76': 'Key 73b589bfd5910adcb769b294ab98d70717fded76 not found in /da5_fast/All.sha1c/commit_115.tch'}

 20%|█████████████████████████▍                                                                                                     | 659/3294 [11:24<45:46,  1.04s/it]

Got Errors {'d27197fe9bd1d143a83f86955120314c6c509035': 'Key d27197fe9bd1d143a83f86955120314c6c509035 not found in /da5_fast/All.sha1c/commit_82.tch'}

 26%|█████████████████████████████████                                                                                              | 857/3294 [14:51<42:27,  1.05s/it]

Got Errors {'554c054531c7d94672743ddf0379e4e387a046a4': 'Key 554c054531c7d94672743ddf0379e4e387a046a4 not found in /da5_fast/All.sha1c/commit_85.tch'}

 28%|███████████████████████████████████▏                                                                                           | 913/3294 [16:15<52:53,  1.33s/it]

Got Errors {'76d85f5378bb8518726ef762865e1da0ac68bf57': 'Key 76d85f5378bb8518726ef762865e1da0ac68bf57 not found in /da5_fast/All.sha1c/commit_118.tch', '76f60b23896f4afabc46e0d521e4390279d82e4e': 'Key 76f60b23896f4afabc46e0d521e4390279d82e4e not found in /da5_fast/All.sha1c/commit_118.tch'}

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 3041/3294 [53:15<04:25,  1.05s/it]

Got Errors {'30cbab387477cf6acb51b95ef8672a70587bb639': 'Key 30cbab387477cf6acb51b95ef8672a70587bb639 not found in /da5_fast/All.sha1c/commit_48.tch'}

 93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 3047/3294 [53:22<04:18,  1.05s/it]

Got Errors {'381401983cd368eaf4892045a5368659c32b3b13': 'Key 381401983cd368eaf4892045a5368659c32b3b13 not found in /da5_fast/All.sha1c/commit_56.tch'}

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 3067/3294 [53:43<03:57,  1.05s/it]

Got Errors {'51b664ec7d42293e30323e990aa70edb25c525e1': 'Key 51b664ec7d42293e30323e990aa70edb25c525e1 not found in /da5_fast/All.sha1c/commit_81.tch'}

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 3108/3294 [54:26<03:13,  1.04s/it]

Got Errors {'7e1dbce186d5ee5ee6f6afdbd7d88171cb184895': 'Key 7e1dbce186d5ee5ee6f6afdbd7d88171cb184895 not found in /da5_fast/All.sha1c/commit_126.tch'}

 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 3113/3294 [54:31<03:10,  1.05s/it]

Got Errors {'84241957468d12f11b545c04f18c9f48df0990fd': 'Key 84241957468d12f11b545c04f18c9f48df0990fd not found in /da5_fast/All.sha1c/commit_4.tch'}

 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 3187/3294 [55:48<01:51,  1.04s/it]

Got Errors {'d7bddef686df03fa44945a1ffc884b4d425d741b': 'Key d7bddef686df03fa44945a1ffc884b4d425d741b not found in /da5_fast/All.sha1c/commit_87.tch'}

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 3235/3294 [56:38<01:01,  1.05s/it]

Got Errors {'3f629e21b60d7561175a3787111a844db980438a': 'Key 3f629e21b60d7561175a3787111a844db980438a not found in /da5_fast/All.sha1c/commit_63.tch', '3ffe8c3e3d945f71ba2c0471be73d3a7a96329ad': 'Key 3ffe8c3e3d945f71ba2c0471be73d3a7a96329ad not found in /da5_fast/All.sha1c/commit_63.tch'}

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 3239/3294 [56:42<00:57,  1.04s/it]

Got Errors {'5059cb28bcc45870cd6e44554a6095f5c0534a9c': 'Key 5059cb28bcc45870cd6e44554a6095f5c0534a9c not found in /da5_fast/All.sha1c/commit_80.tch'}

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 3241/3294 [56:44<00:55,  1.04s/it]

Got Errors {'55b35e65bd530f13f60a0e1e4403ad37878c6391': 'Key 55b35e65bd530f13f60a0e1e4403ad37878c6391 not found in /da5_fast/All.sha1c/commit_85.tch'}

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 3242/3294 [56:45<00:54,  1.04s/it]

Got Errors {'5e70837437bc990d6fa5b62843f9e36156224f76': 'Key 5e70837437bc990d6fa5b62843f9e36156224f76 not found in /da5_fast/All.sha1c/commit_94.tch'}

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 3251/3294 [56:55<00:44,  1.04s/it]

Got Errors {'8bf6c6a50e7b46657232e46d5c3208a57e9728f3': 'Key 8bf6c6a50e7b46657232e46d5c3208a57e9728f3 not found in /da5_fast/All.sha1c/commit_11.tch'}

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 3259/3294 [57:03<00:36,  1.04s/it]

Got Errors {'afd119394ef881ee5d003629028bb66e1591269d': 'Key afd119394ef881ee5d003629028bb66e1591269d not found in /da5_fast/All.sha1c/commit_47.tch'}

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 3276/3294 [57:20<00:18,  1.04s/it]

Got Errors {'fe516c8b16c7c12ec345c78928bfebfefda7ebea': 'Key fe516c8b16c7c12ec345c78928bfebfefda7ebea not found in /da5_fast/All.sha1c/commit_126.tch'}

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3294/3294 [57:39<00:00,  1.05s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0042246a0dd64b15adbeea4a0c71a81889dab790,9e111407324e3488fc1baabd994a910a66b6af52,"[669c98590f1720c0a06eea1f0923e0c67cdaefb0, 1c3...",ST John <st--@users.noreply.github.com>,1649313401,+0300,ST John <st--@users.noreply.github.com>,1649313401,+0300,Merge branch 'st/ad_tests2' of github.com:Juli...,0042246a0dd64b15adbeea4a0c71a81889dab790,juliagaussianprocesses_abstractgps.jl
1,00783f9701edb3717125aa16b9e6922e27556595,a169fbf77e10fc6ca25eef05f6119d8b5570c454,[fa67baea5bebacef20a28eb73508d2d44dbb860c],Sharan Yalburgi <sharanyalburgi@gmail.com>,1595875021,+0530,Sharan Yalburgi <sharanyalburgi@gmail.com>,1595875021,+0530,Style fixes\n,00783f9701edb3717125aa16b9e6922e27556595,juliagaussianprocesses_abstractgps.jl

In [4]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '0042246a0dd64b15adbeea4a0c71a81889dab790', 'tree': '9e111407324e3488fc1baabd994a910a66b6af52', 'parent': ['669c98590f1720c0a06eea1f0923e0c67cdaefb0', '1c3366b19b7554a669f5b44be01fb0686ea6d413'], 'author': 'ST John <st--@users.noreply.github.com>', 'author_time': 1649313401, 'author_tz': '+0300', 'committer': 'ST John <st--@users.noreply.github.com>', 'committer_time': 1649313401, 'committer_tz': '+0300', 'message': "Merge branch 'st/ad_tests2' of github.com:JuliaGaussianProcesses/AbstractGPs.jl into st/ad_tests2\n"}

In [5]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [6]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,sicara_tuto-fsl,0042246a0dd64b15adbeea4a0c71a81889dab790,ST John <st--@users.noreply.github.com>,1649313401,Merge branch 'st/ad_tests2' of github.com:Juli...

In [7]:
#mode a means append, so you have all your projects in the same file
yournetid='kbissonn'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github